#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""created 16.03.2021
@author: holger mohr
"""

import json

def main():
    
    with open('/home/mohr/ARC_challenge/ARC_repo_chollet/ARC/data/training/0a938d79.json') as f:
        task_dict = json.load(f)

    print(task_dict['train'][0]['input'][0][5])

if __name__ == '__main__':
    main()
